"""First migration

Revision ID: 6c10d93e4ae3
Revises: 
Create Date: 2020-12-21 22:24:10.031869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c10d93e4ae3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurants_address', table_name='restaurants')
    op.drop_index('ix_restaurants_id', table_name='restaurants')
    op.drop_index('ix_restaurants_name', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index('ix_reviews_id', table_name='reviews')
    op.drop_index('ix_reviews_price', table_name='reviews')
    op.drop_index('ix_reviews_rating', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_rating', 'reviews', ['rating'], unique=False)
    op.create_index('ix_reviews_price', 'reviews', ['price'], unique=False)
    op.create_index('ix_reviews_id', 'reviews', ['id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('avg_price', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_restaurants_name', 'restaurants', ['name'], unique=False)
    op.create_index('ix_restaurants_id', 'restaurants', ['id'], unique=False)
    op.create_index('ix_restaurants_address', 'restaurants', ['address'], unique=False)
    # ### end Alembic commands ###
