"""Change relations

Revision ID: e6d9c2f328c6
Revises: 6c10d93e4ae3
Create Date: 2020-12-23 12:15:45.277729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d9c2f328c6'
down_revision = '6c10d93e4ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
